services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: order_now_pay_later
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_db:/var/lib/postgresql/data/

  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=immanuel
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db

  backend:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/order_now_pay_later
      PORT: 5000

volumes:
  mongo-db:
  postgres_db: